# Generated by Django 4.2.23 on 2025-09-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_types', '0009_alter_categorytype_suffix_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='text',
            field=models.CharField(db_index=True, max_length=9999),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='text',
            field=models.CharField(db_index=True, max_length=9999),
        ),
        migrations.AlterField(
            model_name='spantype',
            name='text',
            field=models.CharField(db_index=True, max_length=9999),
        ),
    ]
